name: Main

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    strategy:
      matrix:
        rust-toolchain: [stable]
        os: [ubuntu-latest, macos-11, windows-latest]
        arch: [amd64, arm64]
        exclude:
          - os: ubuntu-latest
            arch: arm64x
          - os: windows-latest
            arch: arm64
        include:
          - os: ubuntu-latest
            name: linux
            enable_cross: true
            rust_abi: unknown-linux-gnu
          - os: macos-11
            name: darwin
            rust_abi: apple-darwin
            enable_cross: false
          - os: windows-latest
            name: windows
            rust_abi: pc-windows-msvc
            extension: .exe
            enable_cross: false
          - arch: arm64
            rust_arch: aarch64
          - arch: amd64
            rust_arch: x86_64

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install latest Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust-toolchain }}
          target: ${{ matrix.rust_arch }}-${{ matrix.rust_abi }}
          default: true
          override: true

      - name: Extract tag name
        uses: olegtarasov/get-tag@v2.1
        id: tagName

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all --locked --target=${{ matrix.rust_arch }}-${{ matrix.rust_abi }}
          use-cross: ${{ matrix.enable_cross }}

      - name: Package
        run: |
          find . -name viceroy -type f -print
          cd target/debug
          file viceroy${{ matrix.extension }}
          strip viceroy${{ matrix.extension }}
          tar czf viceroy_${{ steps.tagName.outputs.tag }}_${{ matrix.name }}-${{ matrix.arch }}.tar.gz viceroy${{ matrix.extension }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/debug/viceroy_${{ steps.tagName.outputs.tag }}_${{ matrix.name }}-${{ matrix.arch }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
