name: Main

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    strategy:
      matrix:
        rust-toolchain: [stable]
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [amd64, arm64]
        include:
          - os: ubuntu-latest
            name: linux
          - os: macos-latest
            name: darwin
            rust-target: x86_64-apple-darwin
          - os: windows-latest
            name: windows
            extension: .exe
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install latest Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust-toolchain }}
          target: ${{ matrix.rust-target }}
          default: true
          override: true

      - name: Extract tag name
        uses: olegtarasov/get-tag@v2.1
        id: tagName

      - name: Build
        run: |
          cargo build --all --release --locked

      - name: Package
        run: |
          cd target/release        
          strip viceroy${{ matrix.extension }}
          tar czf viceroy_${{ steps.tagName.outputs.tag }}_${{ matrix.name }}-${{ matrix.arch }}.tar.gz viceroy${{ matrix.extension }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/release/viceroy_${{ steps.tagName.outputs.tag }}_${{ matrix.name }}-${{ matrix.arch }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
